name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./ javariya_bootcamp_react.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: surge deploy
        run: |
             export 
             npm run deploy
